spring:
  application:
    name: gym-booking

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_booking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    datatype:
      datetime:
        write-dates-as-timestamps: false
